steps:

  # Docker Build and Tag to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Docker Build

  # Docker Push to GCR
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
    id: Docker Push

  # Deploying app into Compute Engine
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    timeout: 240s
    args: 
      - compute
      - ssh
      - <instance-name>
      - '--project=$PROJECT_ID'
      - '--zone=us-central1-c'
      - '--command=apt-get install docker.io;sudo usermod -a -G docker root;newgrp docker;gcloud auth configure-docker;docker pull $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA; docker run -d -it --name chimera -p 8080:4000 $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME:$SHORT_SHA;docker ps -a'
    id: Deploy app into GCE
  

options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: gcr.io
  _IMAGE_NAME: chimera
  _DEPLOY_REGION: asia-southeast1 // This region for Cloud Run
