---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chimera-app
spec:
  selector:
    matchLabels:
      app: chimera-app
  template:
    metadata:
      labels:
        app: chimera-app
    spec:
      containers:
      - name: chimera-app
        image: gcr.io/<Project-id>/<source-repo>/chimera:TAG
        ports:
          - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: sit-service
spec:
  ports:
  - port: 80
    targetPort: 4000
  type: LoadBalancer
  selector:
    app: chimera-app
---    


